### ISSUE TITLE
multiple connects to server 

### ISSUE THREAD

**Issue by coffeejunk** [MacIrssi/MacIrssi#13]
MacIrssi Version 0.8.6.6 (Build b05ba43)

I use irssi on a server which has irssi proxy enabled. That is why i need to connect to the same server several times. 

config: 
    servers = (
      {
        address = "xyz.com";
        port = "2778";
        password = "xxx";
        autoconnect = "yes";
      },
      {
        address = "xyz.com";
        port = "2779";
        password = "xxx";
        autoconnect = "yes";
      }
    );

When i start MacIrssi I get connected to the first server but not the second. (Workaround www.xyz.com)

**Comment by ghost** [comment]
You can certainly connect twice, it should be the same behaviour as normal Irssi. If those servers are in separate networks it should connect. I use a very similar arrangement to connect to my ZNC instance.

**Comment by coffeejunk** [comment]
I can connect, but the channels of the second entry won't show up.

**Comment by ghost** [comment]
Channels are generally keyed by network, not by server, if these connections represent connections to different networks in the Irssi proxy then I'd advise you set them up similarly in MacIrssi also.

**Comment by joewilliams** [comment]
@daagaak I am using ZNC as well, would you mind sharing a config example of how you connect and auth as multiple users against ZNC?

**Comment by ghost** [comment]
Ok, there's limitations in this because of how Irssi's core stores Servers. Servers are only keyed off hostname and port, so you must vary the hostname or the port in each of your connections to ZNC.

I choose to vary the hostname, you may vary the port. I have a wildcard sub-sub-level DNS domains set up (so *.irc.foo.com). Each of my servers has a different prefix, to properly key them in Irssi.

After that, I just add each ZNC connection to a separate Network. Each network has auto-join channels and auto-commands which can be run on connect.

**Comment by joewilliams** [comment]
Do you just add "/quote PASS XXX:XXX" to your auto-commands?

**Comment by ghost** [comment]
You can add a password to a server using /server and it will append and replace the existing server entry. I'll endeavour to add a password entry in the UI though.

**Comment by atr000** [comment]
irssi, I recall around April or August between the request and actual commit, changed the format which I think might pertain to the problem. Latest build is using 0.8.15-svn, so this is fixed in the core.

Before, if you had a server that had identical host and port, no matter if you used a different pass/arguments AND network (you would think network should be ME), it would throw back an error. The latest dev build of MacIrssi is using one of the fixed builds here as I have to use this type of setup because of ZNC.

Since ZNC offers ONE port for everything, but differentiates via user/pass (no clue how others work), if your client will not allow multiple connections under these circumstances, it won't work.

As of the latest build, you can add server and network but the network nstextinput lacks an option for password; this can be done via /network 

My setup is this: macirssi connects to three instances of the same exact server, my VPS, at an odd port. Beyond the user name and passwords, the nicks are all idential along with IRCNAME. irssi's nice "network" feature allows each of these to be canonicalized into something like EFNet, FreeNode, etc, so it all works out in the end now.

**Comment by ghost** [comment]
As far as I can tell from svn.irssi.org, the servers/networks are still not keyed by password (along with address and port). So you still have to vary either the port or the server name for each ZNC login you want to use.

**Comment by necrogami** [comment]
This was a bug of IRSSI that was fixed in 0.8.15.

**Comment by necrogami** [comment]
http://bugs.irssi.org/index.php?do=details&task_id=554 forgot to tag the irssi bug link.

**Comment by ghost** [comment]
I'm not completely sure that helps, does it? You can only specify password per-server, their change let you put the same server in multiple networks. That wouldn't help you connect to the same ZNC with multiple different passwords.

**Comment by atr000** [comment]
ZNC mildly addresses this via their Wiki but really leaves people who aren't comfortable with setting up this at a loss. Besides compiling the source, this is the #1 asked question on efnet/#znc--usually multiple times a day even though it's not only documented but mentioned many times because most people are used to psyBNC that allows the multi-user behavior. 

Before dagaak fixed this in the prefs, the config via .irssi worked fine to mod this, and it's unfortunately not documented beyond some blog entries, along with the fix above. 

ZNC will never have more than one network per one user, and the ZNC folks have made this clear. 

If you hate "making new users", both *admin and the web module offer a "clone" user which I use, then just change the username and setup a separate network.
