### ISSUE TITLE
Crash at boot up

### ISSUE THREAD

**Issue by jesst** [MacIrssi/MacIrssi#40]
Mac Irssi crashes immediately at start up. I get a pop-up that asks to send a report, but it crashes before I can do anything. 

crash log:
http://pastie.org/1746290

**Comment by ghost** [comment]
Hi, thanks for the report. I'm fairly sure this is one that I've fixed already. Pleas try the beta version available at https://github.com/daagaak/MacIrssi/downloads and see if that fixes your problem.

**Comment by patcon** [comment]
Mine crashes on launch too (even after upping to the dev version). Just wanted to say thanks for the awesome product though! I actively try to convert everyone from Colloquoy when not having any issues :)
(Love the per-channel highlight words by the way -- I don't think even irssi has that!)

```
Process:         MacIrssi [46312]
Path:            /Applications/MacIrssi.app/Contents/MacOS/MacIrssi
Identifier:      MacIrssi
Version:         0.8.6.6 (0.8.6.6)
Code Type:       X86 (Native)
Parent Process:  launchd [103]

Date/Time:       2012-02-08 17:14:29.999 -0500
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          92349 sec
Crashes Since Last Report:           2
Per-App Interval Since Last Report:  9 sec
Per-App Crashes Since Last Report:   -2
Anonymous UUID:                      DAB02E2F-367C-4B74-B912-0C9072D2383D

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Codes: KERN_PROTECTION_FAILURE at 0x000000000000000c
Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Thread 0 Crashed:  Dispatch queue: com.apple.main-thread
0   MacIrssi                        0x00082b6d irc_server_connect + 24
1   MacIrssi                        0x00064ac8 server_connect + 76
2   MacIrssi                        0x000510ed cmd_connect + 52
3   MacIrssi                        0x0006c8a0 signal_emit_real + 290
4   MacIrssi                        0x0006ca81 signal_emit + 163
5   MacIrssi                        0x00098145 autoconnect_servers + 375
6   MacIrssi                        0x00098482 fe_common_core_finish_init + 282
7   MacIrssi                        0x00003469 irssi_main + 2324
8   MacIrssi                        0x00007558 -[AppController awakeFromNib] + 2924
9   com.apple.CoreFoundation        0x95c53984 -[NSSet makeObjectsPerformSelector:] + 196
10  com.apple.AppKit                0x953011cc -[NSIBObjectData nibInstantiateWithOwner:topLevelObjects:] + 1566
11  com.apple.AppKit                0x952ff1a4 loadNib + 257
12  com.apple.AppKit                0x952fe59c +[NSBundle(NSNibLoading) _loadNibFile:nameTable:withZone:ownerBundle:] + 228
13  com.apple.AppKit                0x952fe4ad +[NSBundle(NSNibLoading) loadNibFile:externalNameTable:withZone:] + 158
14  com.apple.AppKit                0x952fe3f8 +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 383
15  com.apple.AppKit                0x952fb1fd NSApplicationMain + 434
16  MacIrssi                        0x00002562 _start + 216
17  MacIrssi                        0x00002489 start + 41

Thread 1:  Dispatch queue: com.apple.libdispatch-manager
0   libSystem.B.dylib               0x97050382 kevent + 10
1   libSystem.B.dylib               0x97050a9c _dispatch_mgr_invoke + 215
2   libSystem.B.dylib               0x9704ff59 _dispatch_queue_invoke + 163
3   libSystem.B.dylib               0x9704fcfe _dispatch_worker_thread2 + 240
4   libSystem.B.dylib               0x9704f781 _pthread_wqthread + 390
5   libSystem.B.dylib               0x9704f5c6 start_wqthread + 30

Thread 2:
0   libSystem.B.dylib               0x9704f412 __workq_kernreturn + 10
1   libSystem.B.dylib               0x9704f9a8 _pthread_wqthread + 941
2   libSystem.B.dylib               0x9704f5c6 start_wqthread + 30

Thread 0 crashed with X86 Thread State (32-bit):
  eax: 0x00000000  ebx: 0x0006c78f  ecx: 0x00000000  edx: 0x00000003
  edi: 0x00000000  esi: 0x00000000  ebp: 0xbffff218  esp: 0xbffff200
   ss: 0x0000001f  efl: 0x00010246  eip: 0x00082b6d   cs: 0x00000017
   ds: 0x0000001f   es: 0x0000001f   fs: 0x00000000   gs: 0x00000037
  cr2: 0x0000000c

Binary Images:
    0x1000 -    0xe7fe7 +MacIrssi 0.8.6.6 (0.8.6.6) <1FB43D04-DBA3-1ECC-79A3-B34E47875C15> /Applications/MacIrssi.app/Contents/MacOS/MacIrssi
  0x15a000 -   0x180fff  libssl.0.9.7.dylib 0.9.7 (compatibility 0.9.7) <9203FADE-F4F2-2245-A32E-BD88819D314D> /usr/lib/libssl.0.9.7.dylib
  0x18f000 -   0x244fe7  libcrypto.0.9.7.dylib 0.9.7 (compatibility 0.9.7) <AACC86C0-86B4-B1A7-003F-2A0AF68973A2> /usr/lib/libcrypto.0.9.7.dylib
  0x28a000 -   0x28bff7 +libgmodule-2.0.0.dylib 1505.0.0 (compatibility 1505.0.0) <A2A45685-5826-84A8-B8DC-25685FA64C0A> /Applications/MacIrssi.app/Contents/Frameworks/libgmodule-2.0.0.dylib
  0x28f000 -   0x298fe7 +libintl.8.0.2.dylib 9.2.0 (compatibility 9.0.0) <B43C25CF-6151-0EE7-7488-165472364CBD> /Applications/MacIrssi.app/Contents/Frameworks/libintl.8.0.2.dylib
  0x29d000 -   0x2b0fff +org.andymatuschak.Sparkle 1.5 Beta 6 (313) <5DF2B8A3-560D-4500-6B85-4215644DE532> /Applications/MacIrssi.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
  0x2be000 -   0x2dcff7 +net.sourceforge.appscript.objc-appscript ??? (0.1.0) <9F796699-3B3A-0011-BFCF-90A5B242D87F> /Applications/MacIrssi.app/Contents/Frameworks/Appscript.framework/Versions/A/Appscript
  0x2fa000 -   0x3cbfe7 +libglib-2.0.0.dylib 1505.0.0 (compatibility 1505.0.0) <FD7B5D55-8077-433D-D0DE-D45B64A2C76E> /Applications/MacIrssi.app/Contents/Frameworks/libglib-2.0.0.dylib
  0x3ea000 -   0x41ffe7 +com.google.GTM ??? (1.0) <3E0CC2F7-0E82-6463-A2BA-B4B037BC300D> /Applications/MacIrssi.app/Contents/Frameworks/GoogleToolboxForMac.framework/Versions/A/GoogleToolboxForMac
0x8fe00000 - 0x8fe4163b  dyld 132.1 (???) <4CDE4F04-0DD6-224E-ACE5-3C06E169A801> /usr/lib/dyld
0x90003000 - 0x900ddfff  com.apple.DesktopServices 1.5.11 (1.5.11) <800F2040-9211-81A7-B438-7712BF51DEE3> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
0x900de000 - 0x900fffe7  com.apple.opencl 12.3.6 (12.3.6) <B4104B80-1CB3-191C-AFD3-697843C6BCFF> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
0x90100000 - 0x90100ff7  com.apple.ApplicationServices 38 (38) <EAF1BC8C-4FD4-4300-B8F7-4B24E49125E2> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
0x90101000 - 0x90105ff7  libGFXShared.dylib ??? (???) <801B2C2C-1692-475A-BAD6-99F85B6E7C25> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
0x90401000 - 0x90429ff7  libxslt.1.dylib 3.24.0 (compatibility 3.0.0) <315D97C2-4E1F-A95F-A759-4A3FA5639E75> /usr/lib/libxslt.1.dylib
0x91380000 - 0x915e5feb  com.apple.security 6.1.2 (55002) <7F00A51B-F22A-0EBC-A321-923472D686BD> /System/Library/Frameworks/Security.framework/Versions/A/Security
0x915e6000 - 0x91633feb  com.apple.DirectoryService.PasswordServerFramework 6.1 (6.1) <00A1A83B-0E7D-D0F4-A643-8C5675C2BB21> /System/Library/PrivateFrameworks/PasswordServer.framework/Versions/A/PasswordServer
0x91634000 - 0x9175afe7  com.apple.WebKit 6534.52 (6534.52.7) <A2FC4307-01BE-DC9E-82FE-68B13F3839A9> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
0x9175b000 - 0x91766ff7  libCSync.A.dylib 545.0.0 (compatibility 64.0.0) <287DECA3-7821-32B6-724D-AE03A9A350F9> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCSync.A.dylib
0x91767000 - 0x91767ff7  liblangid.dylib ??? (???) <FCC37057-CDD7-2AF1-21AF-52A06C4048FF> /usr/lib/liblangid.dylib
0x9177c000 - 0x917b9ff7  com.apple.SystemConfiguration 1.10.8 (1.10.2) <50E4D49B-4F61-446F-1C21-1B2BA814713D> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
0x917ba000 - 0x91adaff3  com.apple.CoreServices.CarbonCore 861.39 (861.39) <5C59805C-AF39-9010-B8B5-D673C9C38538> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
0x91bd5000 - 0x91bd8fe7  libmathCommon.A.dylib 315.0.0 (compatibility 1.0.0) <1622A54F-1A98-2CBE-B6A4-2122981A500E> /usr/lib/system/libmathCommon.A.dylib
0x91ed3000 - 0x91eebff7  com.apple.CFOpenDirectory 10.6 (10.6) <D1CF5881-0AF7-D164-4156-9E9067B7FA37> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
0x91eec000 - 0x91f9aff3  com.apple.ink.framework 1.3.3 (107) <233A981E-A2F9-56FB-8BDE-C2DEC3F20784> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
0x91f9b000 - 0x92057fff  com.apple.ColorSync 4.6.6 (4.6.6) <7CD8B191-039A-02C3-EA5E-4194EC59995B> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSync.framework/Versions/A/ColorSync
0x92058000 - 0x9209aff7  libvDSP.dylib 268.0.1 (compatibility 1.0.0) <8A4721DE-25C4-C8AA-EA90-9DA7812E3EBA> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
0x9209b000 - 0x9209fff7  libGIF.dylib ??? (???) <2123645B-AC89-C4E2-8757-85834CAE3DD2> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
0x920ce000 - 0x92e36fe7  com.apple.WebCore 6534.52 (6534.52.11) <28DB69F5-ACE5-2A67-4DC1-39EED479B56B> /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/WebCore
0x92e37000 - 0x92e94ff7  com.apple.framework.IOKit 2.0 (???) <3DABAB9C-4949-F441-B077-0498F8E47A35> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x92fcf000 - 0x93002fff  libTrueTypeScaler.dylib ??? (???) <0F04DAC3-829A-FA1B-E9D0-1E9505713C5C> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libTrueTypeScaler.dylib
0x93003000 - 0x93056ff7  com.apple.HIServices 1.8.3 (???) <1D3C4587-6318-C339-BD0F-1988F246BE2E> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
0x9309d000 - 0x930deff7  libRIP.A.dylib 545.0.0 (compatibility 64.0.0) <80998F66-0AD7-AD12-B9AF-3E8D2CE6DE05> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/CoreGraphics.framework/Versions/A/Resources/libRIP.A.dylib
0x93242000 - 0x9324eff7  libkxld.dylib ??? (???) <9A441C48-2D18-E716-5F38-CBEAE6A0BB3E> /usr/lib/system/libkxld.dylib
0x93300000 - 0x934c2feb  com.apple.ImageIO.framework 3.0.4 (3.0.4) <027F55DF-7E4E-2310-1536-3F470CB8847B> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A/ImageIO
0x93532000 - 0x935b2feb  com.apple.SearchKit 1.3.0 (1.3.0) <7AE32A31-2B8E-E271-C03A-7A0F7BAFC85C> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
0x935b3000 - 0x935c3ff7  libsasl2.2.dylib 3.15.0 (compatibility 3.0.0) <E276514D-394B-2FDD-6264-07A444AA6A4E> /usr/lib/libsasl2.2.dylib
0x935c4000 - 0x9366cffb  com.apple.QD 3.36 (???) <FA2785A4-BB69-DCB4-3BA3-7C89A82CAB41> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
0x937c1000 - 0x937c7fff  com.apple.CommonPanels 1.2.4 (91) <CE92759E-865E-8A3B-1488-ECD497E4074D> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
0x9393f000 - 0x93943ff7  IOSurface ??? (???) <89D859B7-A26A-A5AB-8401-FC1E01AC7A60> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
0x93944000 - 0x93a0ffef  com.apple.CoreServices.OSServices 359.2 (359.2) <7C16D9C8-6F41-5754-17F7-2659D9DD9579> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
0x93a19000 - 0x93a9bffb  SecurityFoundation ??? (???) <C4506287-1AE2-5380-675D-95B0291AA425> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
0x93a9c000 - 0x93ab1fff  com.apple.ImageCapture 6.1 (6.1) <B909459A-EAC9-A7C8-F2A9-CD757CDB59E8> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
0x93b91000 - 0x93ba1ff7  com.apple.DSObjCWrappers.Framework 10.6 (134) <95DC4010-ECC4-3A75-5DEE-11BB2AE895EE> /System/Library/PrivateFrameworks/DSObjCWrappers.framework/Versions/A/DSObjCWrappers
0x93be6000 - 0x93ce7fe7  libxml2.2.dylib 10.3.0 (compatibility 10.0.0) <C75F921C-F027-6372-A0A1-EDB8A6234331> /usr/lib/libxml2.2.dylib
0x93d21000 - 0x94510557  com.apple.CoreGraphics 1.545.0 (???) <1D9DC7A5-228B-42CB-7018-66F42C3A9BB3> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
0x94511000 - 0x94514ff7  libCGXType.A.dylib 545.0.0 (compatibility 64.0.0) <4D766435-EB76-C384-0127-1D20ACD74076> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/CoreGraphics.framework/Versions/A/Resources/libCGXType.A.dylib
0x94515000 - 0x94531fe3  com.apple.openscripting 1.3.1 (???) <2A748037-D1C0-6D47-2C4A-0562AF799AC9> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
0x94532000 - 0x94534ff7  libRadiance.dylib ??? (???) <5920EB69-8D7F-5EFD-70AD-590FCB5C9E6C> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
0x94554000 - 0x945a4ff7  com.apple.framework.familycontrols 2.0.2 (2020) <596ADD85-79F5-A613-537B-F83B6E19013C> /System/Library/PrivateFrameworks/FamilyControls.framework/Versions/A/FamilyControls
0x9477b000 - 0x9477eff7  libCoreVMClient.dylib ??? (???) <F58BDFC1-7408-53C8-0B08-48BA2F25CA43> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
0x9477f000 - 0x947b0ff7  libGLImage.dylib ??? (???) <0EE86397-A867-0BBA-E5B1-B800E43FC5CF> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
0x947b3000 - 0x9484efe7  com.apple.ApplicationServices.ATS 275.19 (???) <9FA31967-CF14-B033-EB8D-570561D12A13> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
0x9484f000 - 0x948e7fe7  edu.mit.Kerberos 6.5.11 (6.5.11) <F36DB665-A88B-7F5B-6244-6A2E7FFFF668> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
0x948e8000 - 0x949eafe7  libcrypto.0.9.8.dylib 0.9.8 (compatibility 0.9.8) <015563C4-81E2-8C8A-82AC-31B38D904A42> /usr/lib/libcrypto.0.9.8.dylib
0x949eb000 - 0x94a23ff7  com.apple.LDAPFramework 2.0 (120.1) <131ED804-DD88-D84F-13F8-D48E0012B96F> /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP
0x94a24000 - 0x94a67ff7  com.apple.NavigationServices 3.5.4 (182) <8DC6FD4A-6C74-9C23-A4C3-715B44A8D28C> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/NavigationServices.framework/Versions/A/NavigationServices
0x94a68000 - 0x94e9dff7  libLAPACK.dylib 219.0.0 (compatibility 1.0.0) <4D2F47EF-BD32-1E3C-6A0A-438896ADE2BE> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
0x94e9e000 - 0x94ebefe7  libresolv.9.dylib 41.0.0 (compatibility 1.0.0) <BF7FF2F6-5FD3-D78F-77BC-9E2CB2A5E309> /usr/lib/libresolv.9.dylib
0x94fc0000 - 0x94fc0ff7  com.apple.Carbon 150 (152) <8F767518-AD3C-5CA0-7613-674CD2B509C4> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
0x94fc1000 - 0x95004ff7  libGLU.dylib ??? (???) <FB26DD53-03F4-A7D7-8804-EBC5B3B37FA3> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
0x95005000 - 0x950e5fe7  com.apple.vImage 4.1 (4.1) <D029C515-08E1-93A6-3705-DD062A3A672C> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
0x952ea000 - 0x952f8fe7  libz.1.dylib 1.2.3 (compatibility 1.0.0) <33C1B260-ED05-945D-FC33-EF56EC791E2E> /usr/lib/libz.1.dylib
0x952f9000 - 0x95bdcff7  com.apple.AppKit 6.6.8 (1038.36) <A353465E-CFC9-CB75-949D-786F6F7732F6> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
0x95bdd000 - 0x95be6ff7  com.apple.DiskArbitration 2.3 (2.3) <6AA6DDF6-AFC3-BBDB-751A-64AE3580A49E> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
0x95be7000 - 0x95d62fe7  com.apple.CoreFoundation 6.6.6 (550.44) <F88C95CD-1264-782D-A1F5-204739847E93> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
0x95dc2000 - 0x95e23fe7  com.apple.CoreText 151.10 (???) <5C2DEFBE-D54B-4DC7-D456-9ED02880BE98> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/CoreText.framework/Versions/A/CoreText
0x95e24000 - 0x95e2fff7  libGL.dylib ??? (???) <3E34468F-E9A7-8EFB-FF66-5204BD5B4E21> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
0x95e30000 - 0x95eddfe7  libobjc.A.dylib 227.0.0 (compatibility 1.0.0) <9F8413A6-736D-37D9-8EB3-7986D4699957> /usr/lib/libobjc.A.dylib
0x95ede000 - 0x9601bfe7  com.apple.audio.toolbox.AudioToolbox 1.6.7 (1.6.7) <2D31CC6F-32CC-72FF-34EC-AB40CEE496A7> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
0x9602b000 - 0x96030ff7  com.apple.OpenDirectory 10.6 (10.6) <0603680A-A002-D294-DE83-0D028C6BE884> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
0x960ab000 - 0x960bfffb  com.apple.speech.synthesis.framework 3.10.35 (3.10.35) <9F5CE4F7-D05C-8C14-4B76-E43D07A8A680> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
0x96251000 - 0x9625bffb  com.apple.speech.recognition.framework 3.11.1 (3.11.1) <7486003F-8FDB-BD6C-CB34-DE45315BD82C> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
0x962a1000 - 0x962c3fef  com.apple.DirectoryService.Framework 3.6 (621.12) <A4A47C88-138C-A237-88A5-877E5CAB4494> /System/Library/Frameworks/DirectoryService.framework/Versions/A/DirectoryService
0x962c4000 - 0x962d1ff7  com.apple.NetFS 3.2.2 (3.2.2) <DDC9C397-C35F-8D7A-BB24-3D1B42FA5FAB> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
0x96445000 - 0x96457ff7  com.apple.MultitouchSupport.framework 207.11 (207.11) <6FF4F2D6-B8CD-AE13-56CB-17437EE5B741> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
0x96458000 - 0x96504fe7  com.apple.CFNetwork 454.12.4 (454.12.4) <DEDCD006-389F-967F-3405-EDF541F406D7> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
0x96505000 - 0x96569fff  com.apple.htmlrendering 72 (1.1.4) <0D22B190-513B-7FF6-39FC-9D336285DE08> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HTMLRendering.framework/Versions/A/HTMLRendering
0x96591000 - 0x965a2ff7  com.apple.LangAnalysis 1.6.6 (1.6.6) <3036AD83-4F1D-1028-54EE-54165E562650> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
0x965a3000 - 0x965b7fe7  libbsm.0.dylib ??? (???) <B328FA0A-899C-4FC4-F2AC-2FDC08819CD2> /usr/lib/libbsm.0.dylib
0x965b8000 - 0x96622fe7  libstdc++.6.dylib 7.9.0 (compatibility 7.0.0) <411D87F4-B7E1-44EB-F201-F8B4F9227213> /usr/lib/libstdc++.6.dylib
0x96623000 - 0x96692ff7  libvMisc.dylib 268.0.1 (compatibility 1.0.0) <595A5539-9F54-63E6-7AAC-C04E1574B050> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
0x96693000 - 0x966cdfe7  libssl.0.9.8.dylib 0.9.8 (compatibility 0.9.8) <C62A7753-99A2-6782-92E7-6628A6190A90> /usr/lib/libssl.0.9.8.dylib
0x96d4a000 - 0x96d8efe7  com.apple.Metadata 10.6.3 (507.15) <460BEF23-B89F-6F4C-4940-45556C0671B5> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
0x96d8f000 - 0x96d99fe7  com.apple.audio.SoundManager 3.9.3 (3.9.3) <DE0E0EF6-8190-3F65-6BDD-5AC9D8A025D6> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CarbonSound.framework/Versions/A/CarbonSound
0x96d9a000 - 0x96da5ff7  com.apple.CrashReporterSupport 10.6.7 (258) <8F3E7415-1FFF-0C20-2EAB-6A23B9728728> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
0x96da6000 - 0x96dadff3  com.apple.print.framework.Print 6.1 (237.1) <F5AAE53D-5530-9004-A9E3-2C1690C5328E> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
0x96dae000 - 0x96f30fe7  libicucore.A.dylib 40.0.0 (compatibility 1.0.0) <D5980817-6D19-9636-51C3-E82BAE26776B> /usr/lib/libicucore.A.dylib
0x96f31000 - 0x97025ff7  libiconv.2.dylib 7.0.0 (compatibility 7.0.0) <061ABF36-8BA9-79C1-6CE7-EC69A4998F51> /usr/lib/libiconv.2.dylib
0x97029000 - 0x971d0ff7  libSystem.B.dylib 125.2.11 (compatibility 1.0.0) <2DCD13E3-1BD1-6F25-119A-3863A3848B90> /usr/lib/libSystem.B.dylib
0x973f3000 - 0x973f4ff7  com.apple.audio.units.AudioUnit 1.6.7 (1.6.7) <838E1760-F7D9-3239-B3A8-20E25EFD1379> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
0x97415000 - 0x97739fef  com.apple.HIToolbox 1.6.5 (???) <21164164-41CE-61DE-C567-32E89755CB34> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
0x97746000 - 0x97748ff7  com.apple.securityhi 4.0 (36638) <6118C361-61E7-B34E-93DB-1B88108F8F18> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
0x97749000 - 0x97855ff7  libGLProgrammability.dylib ??? (???) <04D7E5C3-B0C3-054B-DF49-3B333DCDEE22> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLProgrammability.dylib
0x97856000 - 0x9789aff3  com.apple.coreui 2 (114) <2234855E-3BED-717F-0BFA-D1A289ECDBDA> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
0x978cc000 - 0x97946fff  com.apple.audio.CoreAudio 3.2.6 (3.2.6) <156A532C-0B60-55B0-EE27-D02B82AA6217> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
0x97947000 - 0x9798dff7  libauto.dylib ??? (???) <29422A70-87CF-10E2-CE59-FEE1234CFAAE> /usr/lib/libauto.dylib
0x97999000 - 0x97d04ff7  com.apple.QuartzCore 1.6.3 (227.37) <E323A5CC-499E-CA9E-9BC3-537231449CAA> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
0x97d05000 - 0x97d05ff7  com.apple.CoreServices 44 (44) <51CFA89A-33DB-90ED-26A8-67D461718A4A> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
0x97d06000 - 0x97dbffe7  libsqlite3.dylib 9.6.0 (compatibility 9.0.0) <52438E77-55D1-C231-1936-76F1369518E4> /usr/lib/libsqlite3.dylib
0x97e56000 - 0x97e7cffb  com.apple.DictionaryServices 1.1.2 (1.1.2) <43E1D565-6E01-3681-F2E5-72AE4C3A097A> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
0x97e96000 - 0x97f28fe7  com.apple.print.framework.PrintCore 6.3 (312.7) <7410D1B2-655D-68DA-D4B9-2C65747B6817> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
0x97f29000 - 0x97f37ff7  com.apple.opengl 1.6.13 (1.6.13) <025A905D-C1A3-B24A-1585-37C328D77148> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
0x98228000 - 0x98263feb  libFontRegistry.dylib ??? (???) <AD45365E-A3EA-62B8-A288-1E13DBA22B1B> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
0x98264000 - 0x982a4ff3  com.apple.securityinterface 4.0.1 (40418) <FED0C1B5-469E-ADFF-308E-C10B6A68AE45> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
0x98321000 - 0x98321ff7  com.apple.Accelerate.vecLib 3.6 (vecLib 3.6) <ABF97DA4-3BDF-6FFD-6239-B023CA1F7974> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
0x98322000 - 0x98529feb  com.apple.AddressBook.framework 5.0.4 (883) <E26855A0-8CEF-8C81-F963-A2BF9E47F5C8> /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
0x9852a000 - 0x985a1ff3  com.apple.backup.framework 1.2.2 (1.2.2) <D65F2FCA-15EB-C200-A08F-7DC4089DA6A2> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
0x985a2000 - 0x985a3ff7  com.apple.TrustEvaluationAgent 1.1 (1) <2D970A9B-77E8-EDC0-BEC6-7580D78B2843> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
0x985a5000 - 0x985c4ff7  com.apple.CoreVideo 1.6.2 (45.6) <EB53CAA4-5EE2-C356-A954-5775F7DDD493> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
0x985c5000 - 0x98836fef  com.apple.Foundation 6.6.8 (751.63) <69B3441C-B196-F2AD-07F8-D8DD24E4CD8C> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
0x98837000 - 0x988d4fe3  com.apple.LaunchServices 362.3 (362.3) <15B47388-16C8-97DA-EEBB-1709E136169E> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
0x988dd000 - 0x988f8ff7  libPng.dylib ??? (???) <25DF2360-BFD3-0165-51AC-0BDAF7899DEC> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
0x98964000 - 0x98964ff7  com.apple.Accelerate 1.6 (Accelerate 1.6) <3891A689-4F38-FACD-38B2-4BF937DE30CF> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
0x98965000 - 0x98a1dfeb  libFontParser.dylib ??? (???) <D57D3834-9395-FD58-092A-49B3708E8C89> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
0x9907e000 - 0x990b1ff7  com.apple.AE 496.5 (496.5) <BF9673D5-2419-7120-26A3-83D264C75222> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
0x990b4000 - 0x990d8ff7  libJPEG.dylib ??? (???) <EA97DEC5-6E16-B51C-BF55-F6E8D23526AD> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
0x99166000 - 0x991a0ff7  libcups.2.dylib 2.8.0 (compatibility 2.0.0) <6875335E-0993-0D77-4E80-41763A8477CF> /usr/lib/libcups.2.dylib
0x991a1000 - 0x995f2fef  com.apple.RawCamera.bundle 3.7.1 (570) <AF94D180-5E0F-10DF-0CB2-FD8EDB110FA2> /System/Library/CoreServices/RawCamera.bundle/Contents/MacOS/RawCamera
0x996d2000 - 0x996d8fe7  com.apple.CommerceCore 1.0 (9.1) <521D067B-3BDA-D04E-E1FA-CFA526C87EB5> /System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Frameworks/CommerceCore.framework/Versions/A/CommerceCore
0x998d7000 - 0x99920fe7  libTIFF.dylib ??? (???) <579DC328-567D-A74C-4BCE-1D1C729E3F6D> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
0x999a0000 - 0x99acefe7  com.apple.CoreData 102.1 (251) <87FE6861-F2D6-773D-ED45-345272E56463> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
0x99acf000 - 0x99acfff7  com.apple.vecLib 3.6 (vecLib 3.6) <FF4DC8B6-0AB0-DEE8-ADA8-7B57645A1F36> /System/Library/Frameworks/vecLib.framework/Versions/A/vecLib
0x99b27000 - 0x99f3dff7  libBLAS.dylib 219.0.0 (compatibility 1.0.0) <9D89FCB3-24C9-8FCF-DB49-27B184AC3222> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
0x99f3e000 - 0x99f3eff7  com.apple.Cocoa 6.6 (???) <5A785062-1ABB-2A54-BAAC-8FEF95275E05> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
0x99f3f000 - 0x9a189fef  com.apple.JavaScriptCore 6534.52 (6534.52.7) <AF71FCC7-B8BF-2DA6-C538-6B7C47F95B2D> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
0x9ab38000 - 0x9ab3bffb  com.apple.help 1.3.2 (41.1) <8AC20B01-4A3B-94BA-D8AF-E39034B97D8C> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
0xc0000000 - 0xc000efef +com.growl.growlwithinstallerframework 0.7.6 (0.7.6) /Applications/MacIrssi.app/Contents/Frameworks/Growl-WithInstaller.framework/Versions/A/Growl-WithInstaller
0xffff0000 - 0xffff1fff  libSystem.B.dylib ??? (???) <2DCD13E3-1BD1-6F25-119A-3863A3848B90> /usr/lib/libSystem.B.dylib

Model: MacBookPro7,1, BootROM MBP71.0039.B0B, 2 processors, Intel Core 2 Duo, 2.4 GHz, 8 GB, SMC 1.62f6
Graphics: NVIDIA GeForce 320M, NVIDIA GeForce 320M, PCI, 256 MB
Memory Module: global_name
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8D), Broadcom BCM43xx 1.0 (5.10.131.42.4)
Bluetooth: Version 2.4.5f3, 2 service, 19 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en1
Serial ATA Device: ST95005620AS, 465.76 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: Internal Memory Card Reader, 0x05ac  (Apple Inc.), 0x8403, 0x26100000 / 2
USB Device: Built-in iSight, 0x05ac  (Apple Inc.), 0x8507, 0x24600000 / 2
USB Device: BRCM2046 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0x06600000 / 4
USB Device: Bluetooth USB Host Controller, 0x05ac  (Apple Inc.), 0x8213, 0x06610000 / 6
USB Device: IR Receiver, 0x05ac  (Apple Inc.), 0x8242, 0x06500000 / 3
USB Device: Apple Internal Keyboard / Trackpad, 0x05ac  (Apple Inc.), 0x0236, 0x06300000 / 2
```

**Comment by x3ro** [comment]
Please submit a crashlog from the current build in case this is still happening.
